version: "3.9"  # optional since v1.27.0
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8123:8080
      - 50003:50000
    container_name: jenkins-commerce
    volumes:
      - ./jenkins_home:/var/jenkins_home