version: "3.9"  # optional since v1.27.0
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8123:8080
      - 50123:50000
    container_name: jenkins-commerce
    volumes:
      - ./jenkins:/var/jenkins_home
  # agent_commerce:
  #   image: jenkins/agent
  #   container_name: agent-commerce
  #   command: java -jar /usr/share/jenkins/agent.jar -jnlpUrl http://jenkins-host:8080/computer/agent-commerce/slave-agent.jnlp -jnlpCredentials admin:nimda
  #   links:
  #     - "jenkins:jenkins-host"
  #   volumes:
  #     - ./agent-commerce:/workspace